### ISSUE TITLE
Default icon is light, should be dark

### ISSUE THREAD

**Issue by bytebuster463** [mpopp75/cookie-sweep#10]
The commit f1d1603 introduces Manifest V3 icons, and it broke my setup.

The [specs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action) specify that (highlight mine):

> This icon displays when a theme using dark **text** is active 

The example shows that the distinction between "icon.png" and "icon-**light**.png", making the "dark" one default.

However, your setup makes the "light" one standard and appearing as "default_icon".
I believe that the default icon should be "dark" one.

I have "light" theme, but for some reason FF 111.0.1 picked the "default" ("light") icon for Toolbar making it invisible. Switching FF to "dark" theme solves the problem, of course.

Patch:

    "default_icon": {`
      "16": "icons/icon-16-dark.png",
      "32": "icons/icon-32-dark.png",
      "64": "icons/icon-64-dark.png"
    },

**Comment by mpopp75** [comment]
Thanks for the report.

The problem should be fixed with the latest commit. Installed addons should be updated very soon via Mozilla Add-Ons.
