### ISSUE TITLE
Extensions doens't remove all cookies

### ISSUE THREAD

**Issue by heubergen** [mpopp75/cookie-sweep#4]
It seems like some cookies are surviving a wipe out even though I didn't whitelist the domain.

For example:

1. Open ricardo.ch
2. Wipe out the cookie storage with Cookie Sweep
3. Cookies are removed according to browser console
4. Check cookie with about:preferences#privacy

**Comment by bytebuster463** [comment]
It seems that cookies having cookie-path not equal to "/" are not removed.

**Comment by mpopp75** [comment]
It appears to me the Cookies are all removed.

Before clearing:
![before](https://user-images.githubusercontent.com/4977998/34691459-ee38e102-f4bc-11e7-8679-cb35e931c197.png)

After clearing:
![after](https://user-images.githubusercontent.com/4977998/34691468-f632a92e-f4bc-11e7-9d25-9c666308c7a7.png)

**Comment by bytebuster463** [comment]
@mpopp75 I think I found a nice STR:

1. Navigate to Bing.com (aka Microsoft Search)
2. Switch to Image Search (2nd link in the top bar)
3. Search for some keyword
4. Click the Cookie Sweep operation button
5. Navigate to about:preferences#privacy and click "remove individual cookies" link
6. Scroll down to bing.com's cookies and expand it

**Actual result:** One cookie remains: Domain=".bing.com"; **Path="/images";** Name="DSQ"; Content="count=0"
The rest of bing.com's cookies are successfully deleted.

**Expected result**: should not be there.
